### ISSUE TITLE
Clarity on adding DB_URL

### ISSUE THREAD

**Issue by astroash** [azayneeva/ws-database-testing#15]
> And don't forget to add these changes:
>``` js
>if (!DB_URL) throw new Error('Enviroment variable DB_URL must be set');
>
>const params = url.parse(DB_URL);
>```

The `db_connection.js` already has these lines:
``` js
if (!process.env.DB_URL) throw new Error('Enviroment variable DB_URL must be set');

const params = url.parse(process.env.DB_URL);
```
It's worth stating that these lines need to be replaced, otherwise they will run into errors with `const params = ...` being set twice.

**Comment by azayneeva** [comment]
that's a very good point! 👍
