### ISSUE TITLE
Reasons for having a test db_build.sql

### ISSUE THREAD

**Issue by astroash** [azayneeva/ws-database-testing#20]
> On larger projects we may have a case where we want to create/remove additional tables within our database to run tests on. We obviously don't want to affect the original database so we need to have a separate db_build.sql file, purely for testing.

This is the reason we would have a test database, not a test `db_build.sql`. You would want to have a test `db_build.sql` so that you can have a range of mock data to test on that you don't want in your production code.

**Comment by azayneeva** [comment]
@astroash , thank you! we've updated the readme :)
