### ISSUE TITLE
reference to mocking

### ISSUE THREAD

**Issue by eliascodes** [azayneeva/ws-database-testing#21]
In [getting started](https://github.com/azayneeva/ws-database-testing/blob/master/README.md#getting-started), you say:
> To test database queries first you need to mock a database, this will stop you accidentally deleting or modifying important data.

What you are doing in this workshop is not mocking. Mocking is when you substitute one component for another an identical interface but none of the side-effects. In this workshop you are creating a real database, just one that happens not to be used for production.

I would suggest removing the reference to "mock", and instead just say that you shouldn't run tests against the same database you use in production for the reasons you give in the rest of the sentence.

**Comment by azayneeva** [comment]
@eliascodes , thank you!  we've deleted the ambiguous word :)
