### ISSUE TITLE
Unclear numbering in readme

### ISSUE THREAD

**Issue by astroash** [azayneeva/ws-database-testing#5]
Theres a lot of numbered lists going on in the readme. If you want numbered steps in each section I would:

- Avoid numbering h2 lines
- If you're numbering h4 lines stick to one sentence. [This section](Create tests folder) is a little tough to follow visually as you have a 3 sentence long numbered h4 with a paragraph underneath.

**Comment by azayneeva** [comment]
@astroash , indeed readme looked cluttered, updated styling now
