### ISSUE TITLE
Step 2 issues

### ISSUE THREAD

**Issue by astroash** [azayneeva/ws-database-testing#6]
Step 2 mentions:

> This workshop is based on the
[pg-workshop](https://github.com/foundersandcoders/pg-workshop) we've just
completed. That's why we assume that you've already set up your local database,
and your config.env contains your database url.

If they have clones your workshop and they are working on it then they will not have a `config.env` as it will be in the other workshop repo

**Comment by azayneeva** [comment]
@astroash , thank you a lot! haven't thought of that at all :) I've added changes to the readme
