### ISSUE TITLE
copied db files? 

### ISSUE THREAD

**Issue by ZooeyMiller** [azayneeva/ws-database-testing#9]
When I've done database testing in the past, I've always used the original files in the `database` directory, rather than creating a specific test copy. 

This has the advantage of not having to maintain 2 files. (with the case of what you have at the moment, if you were to change the db_build file then you would have to change your test db_build file too).

With copying the files you also have to change the `require` statements of the files because they have different names.

I'd recommend swapping to just using the original database files (db_build.js, db_build.sql, db_connection.js), and editing them. 

Because you create a specific test db, and only ever connect to that when testing, there are no problems to this approach.

**Comment by azayneeva** [comment]
thank you for the issues, @ZooeyMiller !
we've updated it in the new version :)
